/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator2;

/**
 *
 * @author SHUAIB
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        display = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        bsign = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        bc = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        bce = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        bdel = new javax.swing.JButton();
        bmul = new javax.swing.JButton();
        bdiv = new javax.swing.JButton();
        bequal = new javax.swing.JButton();
        bplus = new javax.swing.JButton();
        bsub = new javax.swing.JButton();
        b0 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Design Calculator");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        display.setEditable(false);
        display.setBackground(new java.awt.Color(153, 153, 255));
        display.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 36)); // NOI18N
        display.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        display.setText("0");
        display.setAutoscrolls(false);
        display.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(display, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));

        bsign.setBackground(new java.awt.Color(51, 153, 255));
        bsign.setFont(new java.awt.Font("Kaufmann BT", 1, 24)); // NOI18N
        bsign.setForeground(new java.awt.Color(255, 255, 255));
        bsign.setText("+/-");
        bsign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsignActionPerformed(evt);
            }
        });

        b8.setBackground(new java.awt.Color(51, 153, 255));
        b8.setFont(new java.awt.Font("Kaufmann BT", 1, 24)); // NOI18N
        b8.setForeground(new java.awt.Color(255, 255, 255));
        b8.setText("8");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b6.setBackground(new java.awt.Color(51, 153, 255));
        b6.setFont(new java.awt.Font("Kaufmann BT", 1, 24)); // NOI18N
        b6.setForeground(new java.awt.Color(255, 255, 255));
        b6.setText("6");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b9.setBackground(new java.awt.Color(51, 153, 255));
        b9.setFont(new java.awt.Font("Kaufmann BT", 1, 24)); // NOI18N
        b9.setForeground(new java.awt.Color(255, 255, 255));
        b9.setText("9");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        bc.setBackground(new java.awt.Color(51, 153, 255));
        bc.setFont(new java.awt.Font("Kaufmann BT", 1, 24)); // NOI18N
        bc.setForeground(new java.awt.Color(255, 255, 255));
        bc.setText("C");
        bc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(51, 153, 255));
        jButton7.setFont(new java.awt.Font("Kaufmann BT", 1, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText(".");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        b3.setBackground(new java.awt.Color(51, 153, 255));
        b3.setFont(new java.awt.Font("Kaufmann BT", 1, 24)); // NOI18N
        b3.setForeground(new java.awt.Color(255, 255, 255));
        b3.setText("3");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b5.setBackground(new java.awt.Color(51, 153, 255));
        b5.setFont(new java.awt.Font("Kaufmann BT", 1, 24)); // NOI18N
        b5.setForeground(new java.awt.Color(255, 255, 255));
        b5.setText("5");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b2.setBackground(new java.awt.Color(51, 153, 255));
        b2.setFont(new java.awt.Font("Kaufmann BT", 1, 24)); // NOI18N
        b2.setForeground(new java.awt.Color(255, 255, 255));
        b2.setText("2");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b1.setBackground(new java.awt.Color(51, 153, 255));
        b1.setFont(new java.awt.Font("Kaufmann BT", 1, 24)); // NOI18N
        b1.setForeground(new java.awt.Color(255, 255, 255));
        b1.setText("1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        bce.setBackground(new java.awt.Color(51, 153, 255));
        bce.setFont(new java.awt.Font("Kaufmann BT", 1, 24)); // NOI18N
        bce.setForeground(new java.awt.Color(255, 255, 255));
        bce.setText("CE");
        bce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bceActionPerformed(evt);
            }
        });

        b7.setBackground(new java.awt.Color(51, 153, 255));
        b7.setFont(new java.awt.Font("Kaufmann BT", 1, 24)); // NOI18N
        b7.setForeground(new java.awt.Color(255, 255, 255));
        b7.setText("7");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b4.setBackground(new java.awt.Color(51, 153, 255));
        b4.setFont(new java.awt.Font("Kaufmann BT", 1, 24)); // NOI18N
        b4.setForeground(new java.awt.Color(255, 255, 255));
        b4.setText("4");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        bdel.setBackground(new java.awt.Color(51, 153, 255));
        bdel.setFont(new java.awt.Font("Kaufmann BT", 1, 18)); // NOI18N
        bdel.setForeground(new java.awt.Color(255, 255, 255));
        bdel.setText("DEL");
        bdel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdelActionPerformed(evt);
            }
        });

        bmul.setBackground(new java.awt.Color(0, 102, 102));
        bmul.setFont(new java.awt.Font("Kaufmann BT", 1, 24)); // NOI18N
        bmul.setText("*");
        bmul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmulActionPerformed(evt);
            }
        });

        bdiv.setBackground(new java.awt.Color(0, 102, 102));
        bdiv.setFont(new java.awt.Font("Kaufmann BT", 1, 24)); // NOI18N
        bdiv.setText("%");
        bdiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdivActionPerformed(evt);
            }
        });

        bequal.setBackground(new java.awt.Color(255, 153, 0));
        bequal.setFont(new java.awt.Font("Kaufmann BT", 1, 30)); // NOI18N
        bequal.setText("=");
        bequal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bequalActionPerformed(evt);
            }
        });

        bplus.setBackground(new java.awt.Color(0, 102, 102));
        bplus.setFont(new java.awt.Font("Kaufmann BT", 1, 24)); // NOI18N
        bplus.setText("+");
        bplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bplusActionPerformed(evt);
            }
        });

        bsub.setBackground(new java.awt.Color(0, 102, 102));
        bsub.setFont(new java.awt.Font("Kaufmann BT", 1, 30)); // NOI18N
        bsub.setText("-");
        bsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsubActionPerformed(evt);
            }
        });

        b0.setBackground(new java.awt.Color(51, 153, 255));
        b0.setFont(new java.awt.Font("Kaufmann BT", 1, 24)); // NOI18N
        b0.setForeground(new java.awt.Color(255, 255, 255));
        b0.setText("0");
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(bsign, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bequal, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bmul, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(bce, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bc, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bdel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bdiv, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bplus, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bsub, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bc, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bce, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bdiv, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bdel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bmul, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bsub, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bplus, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bequal, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bsign, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcActionPerformed
        // TODO add your handling code here:
        if(display.getText().equals("ERROR"))
            ;//nothing will happen
        else{
            display.setText("0");
            isDot=false;
        }
    }//GEN-LAST:event_bcActionPerformed

    private void bceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bceActionPerformed
        // TODO add your handling code here:
        display.setText("0");
        isOperatorPressed=false;
        whichOperand=false;
        operator=0;
        isDot=false;
    }//GEN-LAST:event_bceActionPerformed

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
      if(display.getText().equals("ERROR"))
          ;//nothing to do
      else
          if(display.getText().equals("0") || isOperatorPressed)
              display.setText("0");
      else
              display.setText(display.getText()+"0");
      isOperatorPressed=false;
              
    }//GEN-LAST:event_b0ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        if(display.getText().equals("ERRROR"))
            ;
        else
            if(display.getText().equals("0") || isOperatorPressed)
                display.setText("1");
        else
                display.setText(display.getText()+"1");
        isOperatorPressed=false;
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
       if(display.getText().equals("ERROR"))
           ;
       else
           if(display.getText().equals("0") || isOperatorPressed)
               display.setText("2");
       else
               display.setText(display.getText()+"2");
       isOperatorPressed=false;
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        if(display.getText().equals("ERROR"))
            ;
        else 
            if(display.getText().equals("0") || isOperatorPressed)
                display.setText("3");
        else
                display.setText(display.getText()+"3");
        isOperatorPressed=false;
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
      if(display.getText().equals("ERROR"))
          ;
      else 
          if(display.getText().equals("0") || isOperatorPressed )
              display.setText("4");
      else
              display.setText(display.getText()+ 4);
      isOperatorPressed=false;
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
      if(display.getText().equals("ERROR"))
          ;
      else
          if(display.getText().equals("0") || isOperatorPressed)
              display.setText("5");
      else
              display.setText(display.getText()+5);
      isOperatorPressed=false; 
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
       if(display.getText().equals("ERROR"))
           ;
       else
           if(display.getText().equals("0")|| isOperatorPressed)
               display.setText("6");
       else
               display.setText(display.getText()+6);
       isOperatorPressed=false;
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        if(display.getText().equals("ERROR"))
            ;
        else
            if(display.getText().equals("0") || isOperatorPressed)
                display.setText("7");
        else
                display.setText(display.getText()+7);
        isOperatorPressed=false;
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
     if(display.getText().equals("ERROR"))
         ;
     else
         if(display.getText().equals("0")|| isOperatorPressed)
             display.setText("8");
     else
             display.setText(display.getText()+8);
     isOperatorPressed=false;
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        if(display.getText().equals("ERROR"))
            ;
        else
            if(display.getText().equals("0") || isOperatorPressed)
                display.setText("9");
        else
                display.setText(display.getText()+9);
        isOperatorPressed=false;
    }//GEN-LAST:event_b9ActionPerformed

    private void bdelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdelActionPerformed
        if(display.getText().equals("ERROR") || display.getText().equals("0") ||isOperatorPressed)
            ;
        else
            if(display.getText().length()>1)
                display.setText(display.getText().substring(0,display.getText().length()-1));
         else
                display.setText("0");
            if(display.getText().indexOf('.')==-1)
                isDot=false;
    }//GEN-LAST:event_bdelActionPerformed

    private void bplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bplusActionPerformed
        if(display.getText().equals("ERROR"))
            ;//nothing will happen
        else{
            if(whichOperand==false){
                data1=Double.parseDouble(display.getText());
                whichOperand=true;
            
            }
            else{
                if(isOperatorPressed)
                    ;//nothing will happen
                else{
                    data2=Double.parseDouble(display.getText());
                    switch(operator)
                    {
                        case 1:
                            data1=data1 + data2;
                            break;
                        case 2:
                            data1=data1-data2;
                            break;
                        case 3:
                            data1=data1 * data2;
                            break;
                        case 4:
                            if(data2!=0.0)
                                data1=data1 / data2;
                            else
                                display.setText("ERROR");
                            break;
                    }
                    if(display.getText().equals("ERROr")){
                        isOperatorPressed=false;
                        operator=0;
                    }
                    else if(data1 == Math.floor(data1))
                        display.setText(""+(int)Math.floor(data1));
                    else
                        display.setText(""+data1);
                    
                }
            }
            if(!display.getText().equals("ERROR")){
                isOperatorPressed=true;
                operator=1;
            }
        }
            
    }//GEN-LAST:event_bplusActionPerformed

    private void bsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsubActionPerformed
                if(display.getText().equals("ERROR"))
            ;//nothing will happen
        else{
            if(whichOperand==false){
                data1=Double.parseDouble(display.getText());
                whichOperand=true;
            
            }
            else{
                if(isOperatorPressed)
                    ;//nothing will happen
                else{
                    data2=Double.parseDouble(display.getText());
                    switch(operator)
                    {
                        case 1:
                            data1=data1 + data2;
                            break;
                        case 2:
                            data1=data1-data2;
                            break;
                        case 3:
                            data1=data1 * data2;
                            break;
                        case 4:
                            if(data2!=0.0)
                                data1=data1 / data2;
                            else
                                display.setText("ERROR");
                            break;
                    }
                    if(display.getText().equals("ERROr")){
                        isOperatorPressed=false;
                        operator=0;
                    }
                    else if(data1 == Math.floor(data1))
                        display.setText(""+(int)Math.floor(data1));
                    else
                        display.setText(""+data1);
                    
                }
            }
            if(!display.getText().equals("ERROR")){
                isOperatorPressed=true;
                operator=2;
            }
                
        }

    }//GEN-LAST:event_bsubActionPerformed

    private void bmulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmulActionPerformed
        if(display.getText().equals("ERROR"))
            ;//nothing will happen
        else{
            if(whichOperand==false){
                data1=Double.parseDouble(display.getText());
                whichOperand=true;
            
            }
            else{
                if(isOperatorPressed)
                    ;//nothing will happen
                else{
                    data2=Double.parseDouble(display.getText());
                    switch(operator)
                    {
                        case 1:
                            data1=data1 + data2;
                            break;
                        case 2:
                            data1=data1-data2;
                            break;
                        case 3:
                            data1=data1 * data2;
                            break;
                        case 4:
                            if(data2!=0.0)
                                data1=data1 / data2;
                            else
                                display.setText("ERROR");
                            break;
                    }
                    if(display.getText().equals("ERROr")){
                        isOperatorPressed=false;
                        operator=0;
                    }
                    else if(data1 == Math.floor(data1))
                        display.setText(""+(int)Math.floor(data1));
                    else
                        display.setText(""+data1);
                    
                }
            }
            if(!display.getText().equals("ERROR")){
                isOperatorPressed=true;
                operator=3;
            }
                
        }
        
    }//GEN-LAST:event_bmulActionPerformed

    private void bdivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdivActionPerformed
        if(display.getText().equals("ERROR"))
            ;//nothing will happen
        else{
            if(whichOperand==false){
                data1=Double.parseDouble(display.getText());
                whichOperand=true;
            
            }
            else{
                if(isOperatorPressed)
                    ;//nothing will happen
                else{
                    data2=Double.parseDouble(display.getText());
                    switch(operator)
                    {
                        case 1:
                            data1=data1 + data2;
                            break;
                        case 2:
                            data1=data1-data2;
                            break;
                        case 3:
                            data1=data1 * data2;
                            break;
                        case 4:
                            if(data2!=0.0)
                                data1=data1 / data2;
                            else
                                display.setText("ERROR");
                            break;
                    }
                    if(display.getText().equals("ERROr")){
                        isOperatorPressed=false;
                        operator=0;
                    }
                    else if(data1 == Math.floor(data1))
                        display.setText(""+(int)Math.floor(data1));
                    else
                        display.setText(""+data1);
                    
                }
            }
            if(!display.getText().equals("ERROR")){
                isOperatorPressed=true;
                operator=4;
            }
                
        }
        
    }//GEN-LAST:event_bdivActionPerformed

    private void bequalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bequalActionPerformed
        if(display.getText().equals("ERROR"))
            ;//nothing will happen
        else{
            if(whichOperand==false){
                data1=Double.parseDouble(display.getText());
                whichOperand=false;
            isOperatorPressed=true;
            }
            else{
                if(isOperatorPressed){
                    data2=data1;
                    switch(operator)
                    {
                        case 1:
                            data1=data1 + data2;
                            break;
                        case 2:
                            data1=data1-data2;
                            break;
                        case 3:
                            data1=data1 * data2;
                            break;
                        case 4:
                            if(data2!=0.0)
                                data1=data1 / data2;
                            else
                                display.setText("ERROR");
                            break;
                    }
                    if(display.getText().equals("ERROr")){
                        isOperatorPressed=false;
                        operator=0;
                    }
                    else if(data1 == Math.floor(data1))
                        display.setText(""+(int)Math.floor(data1));
                    else
                        display.setText(""+data1);
                }  
                else {
                    data2=Double.parseDouble(display.getText());
                    switch(operator)
                    {
                        case 1:
                            data1=data1 + data2;
                            break;
                        case 2:
                            data1=data1-data2;
                            break;
                        case 3:
                            data1=data1 * data2;
                            break;
                        case 4:
                            if(data2!=0.0)
                                data1=data1 / data2;
                            else
                                display.setText("ERROR");
                            break;
                    }
                    if(display.getText().equals("ERROr")){
                        isOperatorPressed=false;
                        operator=0;
                    }
                    else if(data1 == Math.floor(data1))
                        display.setText(""+(int)Math.floor(data1));
                    else
                        display.setText(""+data1);
                }  
                whichOperand=false;
            }
            if(display.getText().equals("ERROR")){
                isOperatorPressed=true;
                operator=5;
            }
                
        }
        
        
    }//GEN-LAST:event_bequalActionPerformed

    private void bsignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsignActionPerformed
        // TODO add your handling code here:
        if(display.getText().equals("ERROR"))
            ;//nothing will happen
        else{
            if(display.getText().equals("0"))
                ;
            else{
                if(Double.parseDouble(display.getText())>0.0)
                    display.setText("-"+display.getText());
                else
                    display.setText(display.getText().substring(1,display.getText().length()));
            }
        }
    }//GEN-LAST:event_bsignActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
           if(display.getText().equals("ERROR"))
            ;//nothing will happen
        else if(display.getText().equals("0")||isOperatorPressed){
            display.setText("0");
            isDot=true;
        }
        else{
            if(isDot)
                ;//nothing will happen
            else
                display.setText(display.getText()+".");
            isDot=true;
        
      
        }
        isOperatorPressed=false;
    }                                   

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        if(display.getText().equals("ERROR"))
            ;//nothing will happen
        else{
            if(whichOperand==false){
                data1=Double.parseDouble(display.getText());
                whichOperand=true;
            
            }
            else{
                if(isOperatorPressed)
                    ;//nothing will happen
                else{
                    data2=Double.parseDouble(display.getText());
                    switch(operator)
                    {
                        case 1:
                            data1=data1 + data2;
                            break;
                        case 2:
                            data1=data1-data2;
                            break;
                        case 3:
                            data1=data1 * data2;
                            break;
                        case 4:
                            if(data2!=0.0)
                                data1=data1 / data2;
                            else
                                display.setText("ERROR");
                            break;
                    }
                    if(display.getText().equals("ERROr")){
                        isOperatorPressed=false;
                        operator=0;
                    }
                    else if(data1 == Math.floor(data1))
                        display.setText(""+(int)Math.floor(data1));
                    else
                        display.setText(""+data1);
                    
                }
            }
            if(!display.getText().equals("ERROR")){
                isOperatorPressed=true;
                operator=1;
            }
                
        }

    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }
    private Double data1,data2;
    private boolean isDot=false; //if Dot pressed then value true
    private boolean isOperatorPressed=false; //when true operator is pressed
    private boolean whichOperand=false; //true for second operand
    private int operator=0; //0-no selection ,1-plus,2-sub,3-multiplay,4-div,5-equal

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton bc;
    private javax.swing.JButton bce;
    private javax.swing.JButton bdel;
    private javax.swing.JButton bdiv;
    private javax.swing.JButton bequal;
    private javax.swing.JButton bmul;
    private javax.swing.JButton bplus;
    private javax.swing.JButton bsign;
    private javax.swing.JButton bsub;
    private javax.swing.JTextField display;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
